apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-quota
spec:
  hard:
    requests.storage: "10Gi"
    requests.ephemeral-storage: "2Gi"
    
    limits.ephemeral-storage: "3Gi"

    elastifile.storageclass.storage.k8s.io/requests.storage: 4Gi
    elastifile.storageclass.storage.k8s.io/persistentvolumeclaims: 3
    pd-standard.storageclass.storage.k8s.io/requests.storage: 6Gi
    ssd-regional.storageclass.storage.k8s.io/persistentvolumeclaims: 7
