namespace: $(NAMESPACE)
commonLabels:
  environment: dev
resources:
#Include all RoleBinding here

#Include All quota policies
- quota/compute-quota.yaml
- quota/storage-quota.yaml
- quota/object-quota.yaml

#Network policies files
- netpol/default-deny.yaml
- netpol/allow-intra-namespace.yaml
- netpol/allow-ingress-traffic.yaml

#Include ingress template 
- ingress/example-ingress-rule.yaml

